config/routes.rb
Collection::Application.routes.draw do
  match '/index/', :to =>  'collection#index'
  root :to  => 'collection#pdf'
  match'/about/', :to => 'collection#about'
  match '/contact/',  :to => 'collection#contact'
  match '/pdf/', :to => 'collection#pdf'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  
  def index
  end
  def about
  end
  def contact
  end
  def pdf
    pdf = File.join(Rails.root, "lib/partsList.pdf")
    send_file(pdf, :filename => "partsList.pdf" ,:disposition => "inline")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/views/collection/about.html.erb
<h1>About us</h1>
<%= link_to "Back to main page", index_path %>
<!-- <%= link_to "Contact", contact_path %> -->
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><br><P>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	
	
	

app/views/collection/contact.html.erb
<%= link_to " Home", index_path%>
<h1>This is a contact page</h1>

app/views/collection/index.html.erb
<div id="navbar">
	<%= stylesheet_link_tag "style"%>
	<%= link_to "Contact Us", contact_path %>
	<%= link_to "Parts List", pdf_path%>
</div>


<%= link_to "About", about_path %>
<% content_for :head do%>
	<title>Welcome to our page.</title>
<% end %>
<p>We are building a whole new experience for you! tune in later to see this site.</p>

<%= image_tag "box1.png", alt: "Box", size: "250x250"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collection</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>